### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Heden** [kakaroto/PL3#16]
When trying to run the "payload_trace_all_sc_calls", i do receive some ETH frames but no XMB (black screen) ?!
I don't know if this an issue coming from my compilation...
Anyway, good work !
PS : You can mail me to discuss about it ;-)

**Comment by kakaroto** [comment]
As I said in the commit log, that payload is very unstable because the amount of syscalls+hypercalls that are all happening at the same time from different threads are all causing some race conditions in the eth-sending code. And I can't use a mutex because some of the interrupt happen in threads in real time.
But I will work on something to fix this tonight, not a real fix, just if I detect another thread sending data, i will discard the current message.. yes, we will loose some data, but it doesn't matter, considering that with the amount of data sent, we already have a very high packet drop rate...

**Comment by kakaroto** [comment]
I'm not working on PL3 anymore, so closing this issue. Reopen if you still need it and want to fix it.
